platform: Any CPU
configuration: Release
os: Visual Studio 2019

before_build:
  - dotnet restore Skrilla\Skrilla.sln

build:
  parallel: true
  project: Skrilla\Skrilla.sln

after_build:
  - dotnet pack ".\Skrilla\Skrilla.OAuth\Skrilla.OAuth.csproj" -c %CONFIGURATION% -o Skrilla

artifacts:
  - path: Skrilla\**\*.*

cache:
  - '%USERPROFILE%\.nuget\packages'

deploy:
  provider: NuGet
  api_key:
    secure: AgpTFC5qJmkZT7dOYZpEz2dQjYm5JZp4F7KmKHfxzUQ=
  skip_symbols: false
  artifact: /.*\.nupkg/
