platform: Any CPU
configuration: Release
os: Visual Studio 2019

before_build:
  - dotnet restore Skrilla\Skrilla.sln

build:
  parallel: true            
  project: Skrilla\Skrilla.sln

after_build:
  - dotnet pack ".\Skrilla\Skrilla.OAuth\Skrilla.OAuth.csproj" -c %CONFIGURATION% -o ..\artifacts

artifacts:
  - path: artifacts\**\*.*
  
cache:
  - '%USERPROFILE%\.nuget\packages'
  
deploy:
  provider: NuGet
  api_key:
    secure: az+/lqhvaiqGOrTYIwgA1prJVMhDPayxs2HLYSSIgrs=
  skip_symbols: false
  artifact: /.*\.nupkg/
