version: '0.1.2-beta-{build}'

platform: Any CPU
configuration: Release
os: Visual Studio 2019

before_build:
  - nuget restore -verbosity detailed

build:
  parallel: true            
  project: Skrilla.sln
